[workspace]
resolver = "2"

members = [
    "shame_derive",
    "shame",
    "examples/*",
    "shame_utils",
    "shame_utils/macros",
]

[profile.dev]
split-debuginfo = "unpacked"

# [profile.dev.package.shame]
# opt-level = 3
