[package]
name = "shame_utils_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0.100", features = ["full"] }
quote = "1.0"

[features]
default = ["pretty"]
pretty = []
