[package]
name = "shame_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
shame_utils_macros = { path = "macros" }
shame = { path = "../shame" }
const-str = { version = "0.6.4", features = ["proc"] }

[dev-dependencies]
bytemuck = { version = "1.0", features = ["derive"] }
